852p

diff --git a/.github/workflows/dummy-epg.yml b/.github/workflows/dummy-epg.yml
--- a/.github/workflows/dummy-epg.yml
+++ b/.github/workflows/dummy-epg.yml
@@ -34,27 +34,22 @@ jobs:
 
       - name: List Files After EPG Script
         run: |
-          echo "Listing files in _epg-end directory after script run:"
+          echo "Listing files in _epg-end directory:"
           ls -la scripts/_epg-end/
 
-      - name: Delete Old EPG File
-        run: |
-          echo "Deleting old EPG files..."
-          rm -f scripts/_epg-end/dummy--epg---*.xml  # Deletes any previous EPG file except the newly created one
-
-      - name: Check if New EPG File Exists
-        run: |
-          echo "Checking if new EPG file exists..."
+          echo "Searching for new EPG file..."
           NEW_FILE=$(find scripts/_epg-end/ -name 'dummy--epg---*.xml' -print -quit)
+
           echo "Found file: $NEW_FILE"  # Debugging line to print found file name
+
           if [ -n "$NEW_FILE" ]; then
-            echo "✅ New EPG file exists: $NEW_FILE"
-            git config --global user.name "github-actions[bot]"
-            git config --global user.email "github-actions[bot]@users.noreply.github.com"
-            git add "$NEW_FILE"
-            git commit -m "Updated EPG file: $NEW_FILE"
-            git push origin main
-            echo "✅ Successfully pushed the new EPG file!"
+              echo "✅ New EPG file exists: $NEW_FILE"
+              git config --global user.name "github-actions[bot]"
+              git config --global user.email "github-actions[bot]@users.noreply.github.com"
+              git add "$NEW_FILE"
+              git commit -m "Updated EPG file: $NEW_FILE"
+              git push origin main
+              echo "✅ Successfully pushed the new EPG file!"
           else
-            echo "❌ ERROR: New EPG file not found!"
-            exit 1
+              echo "❌ ERROR: New EPG file not found!"
+              exit 1
